### ISSUE TITLE
Does this output all permutations?

### ISSUE THREAD

**Issue by stoplion** [SeregPie/lodash.combinations#1]
Hello, question about how this works.
Does this output all permutations?
It seems it is missing some..

```
require("lodash.combinations")
const _ = require("lodash"); // lodash is a peer dependency. 


const c = _.combinations(['hey', 'there'], 2)
console.log(c);
```

outputs..
`[["hey", "there"]]`

but should'nt it output 
`[["hey", "there"], ["there", "hey"]]` ?

**Comment by SeregPie** [comment]
Hello.

This function outputs combinations of each item with another item. The order does not matter here. What you need is a permutations function.

Personally I don't use lodash anymore. If I need combinatorics I take a library.

Look there.
https://repl.it/@SeregPie/InsubstantialElderlyOrigin
