### ISSUE TITLE
Add TypeScript types

### ISSUE THREAD

**Issue by SwiftWinds** [SeregPie/lodash.combinations#2]
TypeScript complains when this package is used, even when @types/lodash is installed:

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/12981958/142755619-77a9c80c-caee-4044-b9de-80487cbe8d21.png">

Any way types for lodash.combinations can be added?

**Comment by Kur0x** [comment]
same problem!

**Comment by SeregPie** [comment]
done

**Comment by SwiftWinds** [comment]
Thank you so much!
